from app.models.theme import Theme

DEFAULT_THEMES: list[dict] = [
    {
        "name": "Corporate Blue",
        "slug": "corporate-blue",
        "description": "Professional theme with a deep navy palette — ideal for business reports",
        "is_default": True,
        "company_name": "Northwind Advisory",
        "font_family": "Helvetica",
        "font_size_body": 11,
        "font_size_heading": 20,
        "primary_color": "#003366",
        "secondary_color": "#4A4A4A",
        "accent_color": "#0F766E",
        "background_color": "#FFFFFF",
        "surface_color": "#F8FAFC",
        "muted_color": "#CBD5E1",
        "page_size": "A4",
        "margin_top": 72.0,
        "margin_bottom": 72.0,
        "margin_left": 72.0,
        "margin_right": 72.0,
        "line_spacing": 1.3,
        "columns": 1,
        "header": {
            "enabled": True,
            "text": "Confidential",
            "align": "left",
            "show_logo": False,
            "divider": True,
            "show_page_numbers": False,
        },
        "footer": {
            "enabled": True,
            "text": "Northwind Advisory",
            "align": "left",
            "show_logo": False,
            "divider": True,
            "show_page_numbers": True,
        },
        "markdown_preset": "enterprise",
    },
    {
        "name": "Editorial Warm",
        "slug": "editorial-warm",
        "description": "Generous whitespace and warm accents — magazine-style spread",
        "is_default": False,
        "company_name": "Meridian Research",
        "font_family": "Helvetica",
        "font_size_body": 12,
        "font_size_heading": 24,
        "primary_color": "#B8531C",
        "secondary_color": "#3D3D3D",
        "accent_color": "#7C2D12",
        "background_color": "#FFFFFF",
        "surface_color": "#FFF7ED",
        "muted_color": "#FCD9C6",
        "page_size": "LETTER",
        "margin_top": 96.0,
        "margin_bottom": 96.0,
        "margin_left": 108.0,
        "margin_right": 108.0,
        "line_spacing": 1.5,
        "columns": 1,
        "header": {
            "enabled": False,
            "text": None,
            "align": "left",
            "show_logo": False,
            "divider": False,
            "show_page_numbers": False,
        },
        "footer": {
            "enabled": True,
            "text": "Meridian Research",
            "align": "right",
            "show_logo": False,
            "divider": True,
            "show_page_numbers": True,
        },
        "markdown_preset": "executive",
    },
]


async def seed_themes() -> None:
    if await Theme.find_one() is not None:
        return
    for data in DEFAULT_THEMES:
        await Theme(**data).insert()
